version: '3'
services:
  app:
    container_name: park-pal-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app